includePaths: []
stylesheets:
- https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css
javascripts: []
base_url: https://changelog.eventil.com
deploy:
  server: nu02
  path: /srv/www/changelog.eventil.com
